# -*- coding: utf-8 -*-
"""limpiar_data (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fyp2OanvevK6gth0v5RY6k6G0rRW5ukN

# 1 Carga de datos y exploración inicial
"""

import pandas as pd
#cargar archivo con errores
df=pd.read_csv('energy_transition_dirty.csv')
df.head()

#from google.colab import drive
#drive.mount('/content/drive')

"""#2 Limpieza de datos"""

import numpy as np
# Eliminar espacios en blacon
df.columns = df.columns.str.strip()
df['Country']=df['Country'].str.strip()
df.head()

# Corregir columna 'Year' a tipo válido
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df.head()

# Convertir columnas numéricas
num_cols=['Total_Energy_GWh',
          'Renewable_Energy_GWh',
          'Renewable_Share_percent',
          'CO2_Emissions_kT',
          'Investment_USD_m'
          ]
for col in num_cols:
  df[col]=(
      df[col]
      .astype(str)
      .str.replace(',','.',regex=False)
      .str.extract(r"(\d+\.?\d*)")
  )
  df[col]=pd.to_numeric(df[col],errors='coerce')
df.head()



#Eliminar filas con valores faltantes
df_clean=df.dropna(subset=[
          'Year',
          'Total_Energy_GWh',
          'Renewable_Energy_GWh',
          'Renewable_Share_percent'
])
#verificar que todo este númerico y sin valores negativos
df_clean=df_clean[df_clean['CO2_Emissions_kT']>=0]
df_clean=df_clean[df_clean['Investment_USD_m']>=0]
df_clean.reset_index(drop=True,inplace=True)
df_clean.head()

"""# 3 Guardar dataset limpio"""

df_clean.to_csv('energy_transition_clean.csv',index=False)

"""#4 Visualización de datos

A) Participación de energía renovable por país
"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10, 6))
sns.barplot(
    data=df_clean,
    x='Renewable_Share_percent',
    y='Country',
    estimator='mean',
    errorbar=None,
    palette='viridis'
)
plt.xlabel('Participación (%)')
plt.ylabel('País')
plt.title('Participación de energía renovable por país')
plt.show()

"""B) Evolución del consumo total de energía por país"""

plt.figure(figsize=(12, 6))
sns.lineplot(
    data=df_clean,
    x='Year',
    y='Total_Energy_GWh',
    hue='Country',
    marker='o'
)
plt.ylabel('Gwh')
plt.grid(True)
plt.title('Consumo total de energía a lo largo del tiempo')
plt.show()

"""C) Gráfica circular de inversión por país"""

df_gruped=df_clean.groupby('Country')['Investment_USD_m'].sum().sort_values(ascending=False)
plt.figure(figsize=(8,8))
plt.pie(df_gruped,labels=df_gruped.index,autopct='%1.1f%%',startangle=140)
plt.title('Inversión por pais')
plt.show()



"""D) Relación entre inversión y reducción de CO2"""

plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=df_clean,
    x='Investment_USD_m',
    y='CO2_Emissions_kT',
    hue='Country',
    size="Renewable_Share_percent",
    sizes=(20, 200),
    alpha=0.7
)
plt.xlabel('Inversión (USD millones)')
plt.ylabel('Emisiones de co2 (kt)')
plt.title('Relación entre inversión y reducción de co2')
plt.show()

"""# 5 Convertir CSV a JSON"""

df=pd.read_csv('energy_transition_clean.csv')
df.to_json('energy_transition_clean.json',orient='records')